server:
  port: 8080
app:
  context: /socialmedia

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

spring:
  application:
    name: "socialmedia"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:C2y6yDjf5%2FR%2Bob0N8A7Cgv30VRDJIWEHLM%2B4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw%2FJw%3D%3D@localhost:10255/admin?ssl=true"
      database: "socialmedia"

remote:
  service:
    url: "https://jsonplaceholder.typicode.com"
    users-uri: "/users"
    photos-uri: "/photos"
    albums-uri: "/albums"
    comments-uri: "/comments"
    posts-uri: "/posts"
    user-albums-uri: "/users/%s/albums"